[[main]]
name = "Servicios"
weight = 30
[[main]]
parent = "Servicios"
name = "Coaching Ejecutivo"
url = '/services/coaching-ex/main-raw'
weight = 31
[[main]]
parent = "Servicios"
name = "Coaching Personal"
url = '/services/coaching-per/main'
weight = 32
[[main]]
parent = "Servicios"
name = "PMaaS y CMaaS"
url = '/services/maas'
weight = 33
[[main]]
parent = "Servicios"
name = "Consultoría del Cambio"
url = '/services/consultancy'
weight = 34
