baseURL = 'https://example.org/'
languageCode = 'en-us'
theme = 'arcana'
# sectionPagesMenu = 'main'

[caches]
[caches.images]
dir = ':cacheDir/images'

# [menus]
#   [[menus.main]]
#     name = 'About'
#     pageRef = '/about'
#     weight = 10
#   [[menus.main]]
#     name = 'Contact'
#     pageRef = '/contact'
#     weight = 1
#   [[menus.main]]
#     name = 'Sample'
#     pageRef = '/contact/sample'
#     parent = 'Contact'
#     weight = 2


[services]
[services.googleAnalytics]
id = 'G-25NEQK4KKL'

[params]
author = "Marta Arpa"
description = "Coaching ejecutivo y personal, PMaaS/CMaaS y consultoría del cambio. Empodero líderes, facilito transformaciones profundas y catalizo el potencial de personas y organizaciones."
keywords = "Marta Arpa, coaching ejecutivo, coaching personal, consultoría del cambio, PMaaS, CMaaS, transformación profunda, empoderar líderes, catalizar potencial, desarrollo organizacional, estrategias personalizadas"
